version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      bash -c "composer install &&
               if [ ! -f .env ]; then cp .env.example .env; fi &&
               php artisan migrate &&
               php -S 0.0.0.0:8000 -t public"

  db:
    image: mysql:8.0
    container_name: lumen_db
    restart: always
    environment:
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
